In [86]:
import pandas as pd
import numpy as np

In [87]:
movies=pd.read_csv(r"C:\Users\DELL\Desktop\4 sem\Movie Recomendor System\tmdb_5000_movies.csv")
credit=pd.read_csv(r"C:\Users\DELL\Desktop\4 sem\Movie Recomendor System\tmdb_5000_credits.csv")

In [88]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [89]:
credit.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [90]:

movies= movies.merge(credit,on='title')

In [91]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [92]:
# geners
# id
# key words
# title
# overveiw
# Cast
# Crew

movies=movies[['genres','id','crew','cast','title','overview','keywords']]

In [93]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    4809 non-null   str
 1   id        4809 non-null   int64
 2   crew      4809 non-null   str
 3   cast      4809 non-null   str
 4   title     4809 non-null   str
 5   overview  4806 non-null   str
 6   keywords  4809 non-null   str
dtypes: int64(1), str(6)
memory usage: 37.0 MB

In [94]:
movies.isnull().sum()

genres      0
id          0
crew        0
cast        0
title       0
overview    3
keywords    0
dtype: int64

In [95]:
movies.dropna(inplace=True)

In [96]:
movies.isnull().sum()

genres      0
id          0
crew        0
cast        0
title       0
overview    0
keywords    0
dtype: int64

In [97]:
movies.duplicated().sum()

np.int64(0)

In [98]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [99]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# ['Action','Adventure','fantasy','scify']

In [100]:
import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [101]:
movies['genres'] = movies['genres'].apply(convert)

In [102]:
movies.head()

,genres,id,crew,cast,title,overview,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,"[Adventure, Fantasy, Action]",285,"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,"[Action, Adventure, Crime]",206647,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [103]:
movies['keywords']=movies["keywords"].apply(convert)

In [104]:
movies.head()

,genres,id,crew,cast,title,overview,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel..."

In [105]:
movies['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4804    [{"cast_id": 1, "character": "El Mariachi", "c...
4805    [{"cast_id": 1, "character": "Buzzy", "credit_...
4806    [{"cast_id": 8, "character": "Oliver O\u2019To...
4807    [{"cast_id": 3, "character": "Sam", "credit_id...
4808    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4806, dtype: str

In [106]:
import ast
def convert3(obj):
    count=0
    L=[]
    for i in ast.literal_eval(obj):
        if count!=3:
            L.append(i['name'])
            count=count+1
        else:
            break    
    return L

In [107]:
movies['cast']=movies['cast'].apply(convert3)

In [108]:
movies.head()

,genres,id,crew,cast,title,overview,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[Johnny Depp, Orlando Bloom, Keira Knightley]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi..."
3,"[Action, Crime, Drama, Thriller]",49026,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[Christian Bale, Michael Caine, Gary Oldman]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i..."
4,"[Action, Adventure, Science Fiction]",49529,"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel..."

In [109]:
import ast
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [110]:
movies['crew']=movies['crew'].apply(fetch_director)

In [111]:
movies.head()

,genres,id,crew,cast,title,overview,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,[James Cameron],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,[Gore Verbinski],"[Johnny Depp, Orlando Bloom, Keira Knightley]",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,[Sam Mendes],"[Daniel Craig, Christoph Waltz, Léa Seydoux]",Spectre,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi..."
3,"[Action, Crime, Drama, Thriller]",49026,[Christopher Nolan],"[Christian Bale, Michael Caine, Gary Oldman]",The Dark Knight Rises,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i..."
4,"[Action, Adventure, Science Fiction]",49529,[Andrew Stanton],"[Taylor Kitsch, Lynn Collins, Samantha Morton]",John Carter,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel..."

In [112]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [113]:
movies['overview']=movies['overview'].apply(lambda X:X.split()
                                            )

In [114]:
movies['overview'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [115]:
movies.head()

,genres,id,crew,cast,title,overview,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,[James Cameron],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon..."
1,"[Adventure, Fantasy, Action]",285,[Gore Verbinski],"[Johnny Depp, Orlando Bloom, Keira Knightley]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ..."
2,"[Action, Adventure, Crime]",206647,[Sam Mendes],"[Daniel Craig, Christoph Waltz, Léa Seydoux]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi..."
3,"[Action, Crime, Drama, Thriller]",49026,[Christopher Nolan],"[Christian Bale, Michael Caine, Gary Oldman]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i..."
4,"[Action, Adventure, Science Fiction]",49529,[Andrew Stanton],"[Taylor Kitsch, Lynn Collins, Samantha Morton]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel..."

In [116]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(' ','')for i in x])

In [117]:
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(' ','')for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(' ','')for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(' ','')for i in x])

In [118]:
movies.head()

,genres,id,crew,cast,title,overview,keywords
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,[JamesCameron],"[SamWorthington, ZoeSaldana, SigourneyWeaver]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ..."
1,"[Adventure, Fantasy, Action]",285,[GoreVerbinski],"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad..."
2,"[Action, Adventure, Crime]",206647,[SamMendes],"[DanielCraig, ChristophWaltz, LéaSeydoux]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,"[Action, Crime, Drama, Thriller]",49026,[ChristopherNolan],"[ChristianBale, MichaelCaine, GaryOldman]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden..."
4,"[Action, Adventure, ScienceFiction]",49529,[AndrewStanton],"[TaylorKitsch, LynnCollins, SamanthaMorton]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p..."

In [119]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [120]:
new_movies=movies[['id','title','tags']]

In [121]:
new_movies.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [122]:
new_movies['tags']=new_movies['tags'].apply(lambda x: ' '.join(x))

In [123]:
new_movies.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [124]:
new_movies['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [125]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return ' '.join(y)

In [126]:
new_movies['tags']=new_movies['tags'].apply(lambda x: x.lower())

In [127]:
new_movies['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [75]:
new_movies['tags']=new_movies['tags'].apply(stem)

In [76]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english',max_features=5000)

vectors = cv.fit_transform(new_movies['tags']).toarray()

In [77]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [78]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)

In [79]:
from sklearn.metrics.pairwise import cosine_similarity

Cos=cosine_similarity(vectors)
Cos

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]], shape=(4806, 4806))

In [80]:
Cos[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329], shape=(4806,))

In [81]:
sorted(list(enumerate(Cos[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1214, np.float64(0.28676966733820225)),
 (2405, np.float64(0.26901379342448517)),
 (3728, np.float64(0.2605130246476754)),
 (507, np.float64(0.255608593705383)),
 (539, np.float64(0.2503866978335957))]

In [82]:
def recommend(movie):
    movie_index=new_movies[new_movies['title']== movie].index[0]
    distances=Cos[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movie_list:
        print(new_movies.iloc[i[0]].title)

In [83]:
recommend('Batman')

Batman
Batman & Robin
Batman Begins
Batman Returns
The R.M.

In [84]:
new_movies.iloc[1214]

id                                                     440
title                          Aliens vs Predator: Requiem
tags     a sequel to 2004' alien vs. predator, the icon...
Name: 1214, dtype: object

In [85]:
import pickle
pickle.dump(new_movies,open('movies.pkl','wb'))
pickle.dump(Cos, open('similarity.pkl', 'wb'))

In [129]:
def precision_at_k(movie, k=5):
    # Get recommendations
    movie_index = new_movies[new_movies['title'] == movie].index[0]
    distances = Cos[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:k+1]
    recommendations = [new_movies.iloc[i[0]].title for i in movie_list]
    
    # Get input movie genres
    input_genres = movies[movies['title'] == movie]['genres'].values[0]
    input_genres = set(input_genres)
    
    relevant = 0
    for rec in recommendations:
        rec_genres = movies[movies['title'] == rec]['genres'].values
        if len(rec_genres) > 0:
            rec_genres = set(rec_genres[0])
            if len(input_genres.intersection(rec_genres)) > 0:
                relevant += 1
    
    precision = relevant / k
    return precision

print("Precision@5 for Avatar:", precision_at_k('Avatar'))
print("Precision@5 for Batman:", precision_at_k('Batman'))
print("Precision@5 for Inception:", precision_at_k('Inception'))

Precision@5 for Avatar: 1.0
Precision@5 for Batman: 0.8
Precision@5 for Inception: 1.0

In [130]:
def coverage(sample_size=100):
    import random
    all_movies = new_movies['title'].values
    sample_movies = random.sample(list(all_movies), sample_size)
    
    recommended_set = set()
    for movie in sample_movies:
        try:
            movie_index = new_movies[new_movies['title'] == movie].index[0]
            distances = Cos[movie_index]
            movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
            recs = [new_movies.iloc[i[0]].title for i in movie_list]
            for r in recs:
                recommended_set.add(r)
        except:
            pass
    
    coverage_score = len(recommended_set) / len(all_movies) * 100
    return coverage_score

print(f"Coverage: {coverage():.2f}%")

Coverage: 8.49%

In [131]:
test_movies = ['Avatar', 'Batman', 'Inception', 'Titanic', 'Interstellar']

print("="*45)
print("       MODEL EVALUATION REPORT")
print("="*45)

precisions = []

for movie in test_movies:
    try:
        p = precision_at_k(movie)
        precisions.append(p)
        
        movie_index = new_movies[new_movies['title'] == movie].index[0]
        distances = Cos[movie_index]
        movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
        recs = [new_movies.iloc[i[0]].title for i in movie_list]
        
        print(f"\nMovie           : {movie}")
        print(f"Precision@5     : {p:.2f}")
        print(f"Recommendations : {recs}")
    except:
        print(f"\nMovie : {movie} not found, skipping...")

print("\n" + "="*45)
print(f"  Average Precision@5 : {sum(precisions)/len(precisions):.2f}")
print(f"  Coverage            : {coverage():.2f}%")
print("="*45)

=============================================
       MODEL EVALUATION REPORT
=============================================

Movie           : Avatar
Precision@5     : 1.00
Recommendations : ['Aliens vs Predator: Requiem', 'Aliens', 'Falcon Rising', 'Independence Day', 'Titan A.E.']

Movie           : Batman
Precision@5     : 0.80
Recommendations : ['Batman', 'Batman & Robin', 'Batman Begins', 'Batman Returns', 'The R.M.']

Movie           : Inception
Precision@5     : 1.00
Recommendations : ['12 Rounds', 'RED', 'Abduction', 'Krrish', 'The Animal']

Movie           : Titanic
Precision@5     : 0.80
Recommendations : ['The Notebook', 'Under the Same Moon', 'Ghost Ship', 'The Bounty', 'Pirates of the Caribbean: On Stranger Tides']

Movie           : Interstellar
Precision@5     : 1.00
Recommendations : ['Guardians of the Galaxy', 'Silent Running', 'Space Cowboys', 'The Martian', 'Apollo 13']

=============================================
  Average Precision@5 : 0.92
  Coverage            : 8.53%
=============================================